# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quant',
            field=models.IntegerField(default='1'),
        ),
    ]
