# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 13, 46, 15, 476119)),
        ),
    ]
