# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 16, 37, 43, 804110)),
        ),
    ]
